apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: notification-service
  name: notification-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - image: jagsmdocker/notification-service-0.0.3-snapshot
        imagePullPolicy: IfNotPresent
        name: notification-service
        envFrom:
          - configMapRef:
              name: notification-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: default
spec:
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 8020
  selector:
    app: notification-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  FILTER_APP_EXT_URI: http://152.70.74.89:8000
  NATS_SERVER_URI: nats://nats-server:4222
kind: ConfigMap
metadata:
  name: notification-service
  namespace: default