spring:
  application:
    name: repair-ticket-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    
server:
  port: 8010

resilience4j.circuitbreaker:
    instances:
        all-tickets:
            slidingWindowSize: 10
            
resilience4j.retry:
    instances:
        all-tickets:
            maxAttempts: 3
            waitDuration: 1s
            enableExponentialBackoff: true