apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: water-filter-web-app
  name: water-filter-web-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: water-filter-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: water-filter-web-app
    spec:
      containers:
      - image: jagsmdocker/water-filter-web-app-0.0.3-snapshot
        imagePullPolicy: IfNotPresent
        name: water-filter-web-app
        envFrom:
          - configMapRef:
              name: water-filter-web-app
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: water-filter-web-app
  name: water-filter-web-app
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: water-filter-web-app
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  REPAIR_TICKET_SERVICE_EXT_URI: http://152.70.74.71:8010
  REPAIR_TICKET_SERVICE_URI: http://repair-ticket-service:8010
  NOTIFICATION_SERVICE_EXT_URI: http://152.70.69.14:8020
kind: ConfigMap
metadata:
  name: water-filter-web-app
  namespace: default