pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/Jags-byte/oracle.git'

                dir("water-filter-web-app") {
                    // Run Maven on a Unix agent.
                    sh "mvn -Dmaven.test.failure.ignore=false clean package"
                }

                dir("repair-ticket-service") {
                    // Run Maven on a Unix agent.
                    sh "mvn -Dmaven.test.failure.ignore=false clean package"
                }

                dir("notification-service") {
                    // Run Maven on a Unix agent.
                    sh "mvn -Dmaven.test.failure.ignore=false clean package"
                }
            }
        }
         stage('Build Docker Image') {
            steps {
                dir("water-filter-web-app") {
                    sh "docker build -t jagsmdocker/water-filter-web-app-0.0.2-snapshot ."
                }
                dir("repair-ticket-service") {
                    sh "docker build -t jagsmdocker/repair-ticket-service-0.0.2-snapshot ."
                }
                dir("notification-service") {
                    sh "docker build -t jagsmdocker/notification-service-0.0.2-snapshot ."
                }
            }
         }
 		stage('Push Docker Image') {
 			environment {
 				DOCKER_HUB_LOGIN = credentials('JagsDockerID')
 			}
            steps {
                dir("water-filter-web-app") {
                	sh "docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW"
                	sh "docker push jagsmdocker/water-filter-web-app-0.0.2-snapshot"
                }
                dir("repair-ticket-service") {
                    sh "docker push jagsmdocker/repair-ticket-service-0.0.2-snapshot"
                }
                dir("notification-service") {
                    sh "docker push jagsmdocker/notification-service-0.0.2-snapshot"
                }
            }
         }       
    }
}


