pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/Jags-byte/oracle.git'

                dir("currency-exchange-service") {
                    // Run Maven on a Unix agent.
                    sh "mvn -Dmaven.test.failure.ignore=false clean package"
                }

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    dir("currency-exchange-service") {
                    	//junit '**/target/surefire-reports/TEST-*.xml'
                        archiveArtifacts 'target/*.jar'
                    }
                }
            }
        }
         stage('Build Docker Image') {
            steps {
                dir("currency-exchange-service") {
                    sh "docker build -t jagsmdocker/currency-exchange ."
                }
            }
         }
 		stage('Push Docker Image') {
 			environment {
 				DOCKER_HUB_LOGIN = credentials('JagsDockerID')
 			}
            steps {
                dir("currency-exchange-service") {
                	sh "docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW"
                    sh "docker push jagsmdocker/currency-exchange"
                }
            }
         }       
    }
}


